### PR TITLE
Fix HNa and HRemove toString()

### PR DESCRIPTION
**Pull request by rracariu**
Fixes the string representation of an NA object to be the same as for Zinc.

### CODE REVIEW

**Review by garethj2 — APPROVED** [review]
LGTM. I guess you don't like the square brackets? Any other particular reason for the change other than just nicer presentation?

**Comment by rracariu** [comment]
It was confusing when looking at the result as one could think that you are looking at an array of `NA` `marker` instead of the scalar value NA. Same would go for `HRemove` from what I see - would change that also if that's OK.

**Comment by garethj2** [comment]
Sure. Let's change it in both places then.

**Comment by garethj2** [comment]
Just see the remove. Also approved. LGTM.

**Review by garethj2 — APPROVED** [review]

**Pull request merged**
